### PR TITLE
Error name

### LINKED ISSUE #83: Better error output
## 🚀 Feature Proposal

Add the plugin name to the output of the errors

## Motivation

Right now if a module need a fastify version the error is this one:

> Error: fastify-plugin - expected '<2.12.0' fastify version, '2.12.0' is installed

But I don't know which plugin is throwing the error

## Example

> Error: fastify-module-name - expected '<2.12.0' fastify version, '2.12.0' is installed

### PR DESCRIPTION
**Pull request by Eomm**
FIxes #83 

Is this a major due to the error output?

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -62,7 +64,7 @@ function checkVersion (version) {
   }
 
   if (fastifyVersion && !semver.satisfies(fastifyVersion, version)) {
-    throw new Error(`fastify-plugin - expected '${version}' fastify version, '${fastifyVersion}' is installed`)
+    throw new Error(`fastify-plugin: ${pluginName} - expected '${version}' fastify version, '${fastifyVersion}' is installed`)
```
Comment (jsumners) [inline index.js]: Does the `pluginName` have a default it isn't somehow set?

Comment (Eomm) [reply index.js]: The `checkName` function will provide every time a string-name to assign to the plugin, that I have added to `checkVersion()`'s arguments

Comment (jsumners) [reply index.js]: 👍
